import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{BookOpen,CheckCircle2,ChevronLeft,ChevronRight,Flame,RotateCcw}from'lucide-react';import'./styles.css';
const topics=[
['QA Foundations',['test design','risk-based testing','regression','bug reports','equivalence partitioning','boundary testing','exploratory testing','severity vs priority','test pyramid','quality gates']],
['Python + pytest',['assertions','fixtures','parametrize','mocking','exceptions','fixture scope','markers','coverage','test isolation','CI dependencies']],
['Git + GitHub',['branches','pull requests','rebase','conflicts','revert vs reset','Actions triggers','secrets','code review','commit quality','branch protection']],
['CI/CD + GitHub Actions',['pipeline stages','runners','checkout','Python setup','artifacts','caching','matrix builds','environments','CI debugging','deployment safety']],
['Salesforce Fundamentals',['objects','SOQL','DML','governor limits','permission sets','record access','Flow','sandboxes','metadata','integrations']],
['Apex Testing',['@IsTest','AAA','Test.startTest','Test.stopTest','SeeAllData','bulk tests','assertions','negative paths','test data factories','deployment failures']],
['Playwright UI Automation',['locators','assertions','auto-waiting','fixtures','traces','page objects','network mocking','parallelism','flakiness','cross-browser']],
['API Testing',['status codes','contract tests','authentication','idempotency','pagination','rate limiting','negative tests','data isolation','observability','performance']],
['SFDX + Salesforce CI/CD',['CLI','source format','scratch orgs','org auth','validation','test levels','destructive changes','drift','artifact promotion','rollback']],
['Quality Strategy + Metrics',['defect escape','MTTR','flaky rate','risk matrix','quality ownership','test strategy','observability','quality gates','coverage interpretation','continuous improvement']],
['Interview Lab',['QE mindset','CI debugging','automation tradeoffs','Salesforce testing','API + UI diagnosis','flaky test response','quality metrics','stakeholder communication','root cause','pipeline design']],
];
const qs={
'QA Foundations':[['Which test set gives the strongest basic coverage?',['Happy path only','Positive + negative + boundary + state cases','Only visual tests','Only API tests'],1,'Good coverage includes positive, negative, boundary and state-dependent behavior.'],['What should risk-based testing prioritize?',['Low-impact copy','High-impact/high-risk workflows','Only CSS','Only documentation'],1,'Prioritize business impact and likelihood.'],['A shared auth service changes. What regression is sensible?',['Only the changed line','Critical auth flows and important dependents','Nothing','Only screenshots'],1,'Shared services require regression around important dependents.']],
'Python + pytest':[['How do you assert add(2,3) equals 5 in pytest?',['assert add(2,3)==5','assert add(2,3)=5','expect add(2,3) 5','assertEqual only'],0,'pytest uses Python assert.'],['What are pytest fixtures primarily for?',['Reusable setup/teardown','Git branching','Apex compilation','CSS'],0,'Fixtures centralize reusable test setup and cleanup.'],['Which feature runs one test with many input cases?',['pytest.mark.parametrize','pytest.loop','pytest.repeat','pytest.inputs'],0,'Parametrize generates cases from data.']],
'Git + GitHub':[['How do you isolate a feature?',['Feature branch','Delete main','Force-push main','Tag only'],0,'Feature branches isolate changes.'],['A shared bad commit needs undoing. Which is safer?',['Revert','Reset + force push','Delete main','Delete repo'],0,'Revert creates a new undo commit and preserves shared history.'],['Where should CI secrets live?',['GitHub Actions secrets','Committed YAML','Source code','README'],0,'Secrets should not be committed.']],
'CI/CD + GitHub Actions':[['What is a typical delivery flow?',['Build/test → package → deploy','Deploy → test → build','Deploy only','Delete → deploy'],0,'Validate before promotion.'],['Which key selects the GitHub Actions runner?',['runs-on','runner-name-only','machine','host'],0,'runs-on selects the runner.'],['What helps retain a test report after a run?',['Artifact upload','Print only','Delete it','Commit it'],0,'Artifacts persist files produced by a workflow.']],
'Salesforce Fundamentals':[['What does SOQL query?',['Salesforce records','Git commits','CSS','Python packages'],0,'SOQL is Salesforce Object Query Language.'],['Why do Salesforce governor limits exist?',['Protect shared platform resources','Improve CSS','Replace Git','Create passwords'],0,'They protect resources in a multitenant platform.'],['What is a sandbox used for?',['Non-production development/testing','Production only','Git storage','CI logs'],0,'Sandboxes provide non-production environments.']],
'Apex Testing':[['What annotation marks an Apex test class?',['@IsTest','@pytest','@ApexTest','@TestOnly'],0,'@IsTest identifies Apex test code.'],['Why use Test.startTest()?',['Fresh governor-limit context','Git branch','Browser start','Deploy metadata'],0,'It separates the code-under-test execution context.'],['What should bulk trigger tests include?',['Many records','One record only','No records','Only UI tests'],0,'Bulk tests expose governor-limit and bulkification defects.']],
'Playwright UI Automation':[['Which locator is generally resilient?',['getByRole with accessible name','nth(7)','screen coordinates','random XPath'],0,'Semantic user-facing locators are usually more stable.'],['A UI appears after a request. What is preferable?',['Locator auto-waiting','Fixed 60s sleep','Busy loop','No wait'],0,'Playwright can wait for actionable locator states.'],['A CI-only failure needs rich browser evidence. What helps?',['Playwright trace','README','Git tag','SOQL'],0,'Traces capture execution details.']],
'API Testing':[['Which status commonly means resource created?',['201','301','404','500'],0,'201 Created is standard for successful creation.'],['A payment retry must not duplicate a charge. What concept matters?',['Idempotency','CSS','Git rebase','SOQL'],0,'Idempotency makes safe retries possible.'],['What does HTTP 429 commonly indicate?',['Rate limiting','Created','Not found','Server deleted'],0,'429 commonly means too many requests.']],
'SFDX + Salesforce CI/CD':[['What is Salesforce CLI useful for?',['Repeatable org/metadata/test automation','Only CSS','Only Git hosting','Only Python'],0,'CLI supports development and deployment workflows.'],['Why version Salesforce metadata?',['Reviewable, repeatable deployments','Disable tests','Store passwords','Replace Apex'],0,'Version control makes changes reviewable and reproducible.'],['What is a scratch org?',['Ephemeral development org','Production database','Git tag','Test report'],0,'Scratch orgs are disposable development environments.']],
'Quality Strategy + Metrics':[['What is an escaped defect?',['A defect reaching a later environment/production','A passing test','A commit','A deployment artifact'],0,'Escape metrics track defects not caught earlier.'],['What does MTTR measure?',['Mean time to recovery/repair','Test count','Coverage','Code size'],0,'MTTR measures restoration/recovery time.'],['Does 90% coverage prove zero defects?',['Yes','No','Only in Salesforce','Only in Python'],1,'Coverage is a signal, not proof of correctness.']],
'Interview Lab':[['What is broader than manual test execution in QE?',['Prevention, automation, strategy and feedback','Only clicking UI','Only Selenium','Only writing bugs'],0,'Quality engineering spans the lifecycle.'],['A CI job says command not found. What do you inspect first?',['Setup, PATH, installed dependencies','CSS','Salesforce objects','Logo'],0,'Start with environment and setup evidence.'],['A UI test is flaky. What should you investigate?',['Selectors, timing, data, races, environment','Delete it immediately','Add a 60s sleep','Ignore it'],0,'Flakiness usually has a synchronization, data or environment cause.']]
};
function makeExercises(){let out=[];for(const [module,items] of topics){const base=qs[module];for(let i=0;i<40/4;i++){const b=base[i%base.length];out.push({id:`${module}-${i+1}`,module,title:b[0],question:b[0],choices:b[1],answer:b[2],explanation:b[3],xp:20});}}return out.concat(Array.from({length:20},(_,i)=>({id:'capstone-'+i,module:'Capstone',title:['CI debugging','Apex bulk test','Playwright stability','API negative paths','QE pipeline'][i%5],question:['A GitHub Actions job cannot find pytest. What is the first thing you inspect?','A trigger fails with 200 records. What should your test cover?','A locator uses nth-child and flakes. What should replace it?','A POST endpoint must handle malformed input and duplicates. What should you test?','Design the high-level Salesforce QE pipeline.'][i%5],choices:['Environment/setup, dependencies and PATH','Only one record','Semantic locator such as role/test-id','Auth, validation and idempotency','PR checks → tests/validation → review → deployment → verification'],answer:0,explanation:'Use evidence, isolate the layer, test the relevant failure mode, and protect production with controlled promotion.',xp:30})))}
const exercises=makeExercises();const modules=[...new Set(exercises.map(x=>x.module))];const KEY='qe-progress-v1';
function App(){const [s,setS]=useState(()=>JSON.parse(localStorage.getItem(KEY)||'{"done":{},"xp":0}'));const [m,setM]=useState('All');const [i,setI]=useState(0);const [sel,setSel]=useState(null);useEffect(()=>localStorage.setItem(KEY,JSON.stringify(s)),[s]);const list=useMemo(()=>exercises.filter(x=>m==='All'||x.module===m),[m]);const e=list[i]||list[0];const pct=Math.round(Object.keys(s.done).length/exercises.length*100);const answer=n=>{if(sel!==null)return;setSel(n);if(n===e.answer&&!s.done[e.id])setS({...s,done:{...s.done,[e.id]:1},xp:s.xp+e.xp})};const next=()=>{setI(Math.min(i+1,list.length-1));setSel(null)};const prev=()=>{setI(Math.max(i-1,0));setSel(null)};return <><header><div><b>Salesforce Quality Engineer Bootcamp</b><small>120+ interactive exercises · mobile-first PWA</small></div><button onClick={()=>{localStorage.removeItem(KEY);location.reload()}}><RotateCcw size={14}/> Reset</button></header><main><section className="hero"><div className="card"><small>YOUR PROGRESS</small><h1>Interview-ready QE training</h1><p>QA → Python/pytest → GitHub Actions → Salesforce → Apex → Playwright → APIs → SFDX/CI/CD → quality strategy → interview lab.</p><div className="bar"><i style={{width:pct+'%'}}/></div><b>{pct}% complete</b></div><div className="card stats"><div><Flame/><b>{s.xp}</b><small>XP</small></div><div><CheckCircle2/><b>{Object.keys(s.done).length}</b><small>done</small></div><div><BookOpen/><b>{exercises.length}</b><small>exercises</small></div></div></section><div className="layout"><aside className="card"><b>Curriculum</b><div className={'module '+(m==='All'?'active':'')} onClick={()=>{setM('All');setI(0);setSel(null)}}>All <span>{exercises.length}</span></div>{modules.map(x=><div className={'module '+(m===x?'active':'')} onClick={()=>{setM(x);setI(0);setSel(null)}} key={x}>{x}<span>{exercises.filter(e=>e.module===x).length}</span></div>)}</aside><article className="card"><div className="tag">{e.module} · {i+1}/{list.length}</div><h2>{e.title}</h2><div className="question">{e.question}</div><div className="choices">{e.choices.map((c,n)=><button className={'choice '+(sel!==null&&n===e.answer?'correct':'')+(sel!==null&&n===sel&&n!==e.answer?' wrong':'')} onClick={()=>answer(n)} key={c}>{String.fromCharCode(65+n)}. {c}</button>)}</div>{sel!==null&&<div className="feedback"><b>{sel===e.answer?'Correct':'Review'}</b><p>{e.explanation}</p></div>}<div className="actions"><button onClick={prev} disabled={i===0}><ChevronLeft/>Previous</button><button className="primary" onClick={next} disabled={i===list.length-1}>Next<ChevronRight/></button></div></article></div><footer>Progress is stored locally on your device. No account or backend required.</footer></main></>};createRoot(document.getElementById('root')).render(<App/>);
